import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect } from "react";

/**
 * Legacy /scan?field_id=...&type=domination|respawn&point=alpha&faction=blue
 * dispatcher. QR codes generated by the Tactical QR Generator resolve here
 * and are re-routed to the concrete /capture or /spawn flow.
 */
export const Route = createFileRoute("/scan")({
  head: () => ({
    meta: [
      { title: "SpartanOps · Scan" },
      { name: "robots", content: "noindex,nofollow" },
    ],
  }),
  validateSearch: (s: Record<string, unknown>) => ({
    field_id: typeof s.field_id === "string" ? s.field_id : (typeof s.field === "string" ? s.field : ""),
    type: typeof s.type === "string" ? s.type : "",
    point: typeof s.point === "string" ? s.point : "",
    faction: typeof s.faction === "string" ? s.faction : "",
  }),
  component: ScanPage,
});

function ScanPage() {
  const { field_id, type, point } = Route.useSearch();
  const navigate = useNavigate();

  useEffect(() => {
    const field = resolveQrField(field_id || "");
    if (type === "domination" && point) {
      navigate({ to: "/capture", search: { field, point } as any, replace: true });
    } else if (type === "respawn") {
      navigate({ to: "/spawn", search: { field } as any, replace: true });
    } else if (field && point) {
      navigate({ to: "/capture", search: { field, point } as any, replace: true });
    } else {
      // Unknown QR — send them to the lobby entry.
      navigate({ to: "/join", search: { field_id: field } as any, replace: true });
    }
  }, [field_id, type, point, navigate]);

  return (
    <div style={{ minHeight: "100vh", background: "#0b0d09", color: "#ece3c4", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "monospace", letterSpacing: "0.2em", fontSize: 12 }}>
      ROUTING…
    </div>
  );
}

function isQrPlaceholder(raw: string): boolean {
  const value = raw.trim();
  const lower = value.toLowerCase();
  return (
    !value ||
    value.includes("[") ||
    value.includes("]") ||
    value.includes("<") ||
    value.includes(">") ||
    lower === "field_uuid" ||
    lower === "field_id" ||
    lower === "mission_uuid" ||
    lower === "mission_id"
  );
}

function activeLobbyId(): string {
  if (typeof window === "undefined") return "";
  try {
    const raw = window.localStorage.getItem("spartanops.active_session");
    if (!raw) return "";
    const parsed = JSON.parse(raw) as { lobbyId?: unknown; authenticated?: unknown };
    return parsed?.authenticated && typeof parsed.lobbyId === "string" ? parsed.lobbyId.trim() : "";
  } catch {
    return "";
  }
}

function resolveQrField(raw: string): string {
  const value = raw.trim();
  if (!isQrPlaceholder(value)) return value;
  return activeLobbyId() || value;
}
