/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SpawnRouteImport } from './routes/spawn'
import { Route as SpartanopsRouteImport } from './routes/spartanops'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as PrintRouteImport } from './routes/print'
import { Route as MisijaRouteImport } from './routes/misija'
import { Route as LokacijaRouteImport } from './routes/lokacija'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as DogodkiRouteImport } from './routes/dogodki'
import { Route as DevPreviewRouteImport } from './routes/dev-preview'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ArhivRouteImport } from './routes/arhiv'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminPregledRouteImport } from './routes/admin-pregled'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendReservationRouteImport } from './routes/api/send-reservation'
import { Route as ApiSendInquiryRouteImport } from './routes/api/send-inquiry'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SpawnRoute = SpawnRouteImport.update({
  id: '/spawn',
  path: '/spawn',
  getParentRoute: () => rootRouteImport,
} as any)
const SpartanopsRoute = SpartanopsRouteImport.update({
  id: '/spartanops',
  path: '/spartanops',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const MisijaRoute = MisijaRouteImport.update({
  id: '/misija',
  path: '/misija',
  getParentRoute: () => rootRouteImport,
} as any)
const LokacijaRoute = LokacijaRouteImport.update({
  id: '/lokacija',
  path: '/lokacija',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const DogodkiRoute = DogodkiRouteImport.update({
  id: '/dogodki',
  path: '/dogodki',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPreviewRoute = DevPreviewRouteImport.update({
  id: '/dev-preview',
  path: '/dev-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ArhivRoute = ArhivRouteImport.update({
  id: '/arhiv',
  path: '/arhiv',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPregledRoute = AdminPregledRouteImport.update({
  id: '/admin-pregled',
  path: '/admin-pregled',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendReservationRoute = ApiSendReservationRouteImport.update({
  id: '/api/send-reservation',
  path: '/api/send-reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendInquiryRoute = ApiSendInquiryRouteImport.update({
  id: '/api/send-inquiry',
  path: '/api/send-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-pregled': typeof AdminPregledRoute
  '/archive': typeof ArchiveRoute
  '/arhiv': typeof ArhivRoute
  '/capture': typeof CaptureRoute
  '/dev-preview': typeof DevPreviewRoute
  '/dogodki': typeof DogodkiRoute
  '/intel': typeof IntelRoute
  '/join': typeof JoinRoute
  '/lokacija': typeof LokacijaRoute
  '/misija': typeof MisijaRoute
  '/print': typeof PrintRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spartanops': typeof SpartanopsRoute
  '/spawn': typeof SpawnRoute
  '/updates': typeof UpdatesRoute
  '/api/send-inquiry': typeof ApiSendInquiryRoute
  '/api/send-reservation': typeof ApiSendReservationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-pregled': typeof AdminPregledRoute
  '/archive': typeof ArchiveRoute
  '/arhiv': typeof ArhivRoute
  '/capture': typeof CaptureRoute
  '/dev-preview': typeof DevPreviewRoute
  '/dogodki': typeof DogodkiRoute
  '/intel': typeof IntelRoute
  '/join': typeof JoinRoute
  '/lokacija': typeof LokacijaRoute
  '/misija': typeof MisijaRoute
  '/print': typeof PrintRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spartanops': typeof SpartanopsRoute
  '/spawn': typeof SpawnRoute
  '/updates': typeof UpdatesRoute
  '/api/send-inquiry': typeof ApiSendInquiryRoute
  '/api/send-reservation': typeof ApiSendReservationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-pregled': typeof AdminPregledRoute
  '/archive': typeof ArchiveRoute
  '/arhiv': typeof ArhivRoute
  '/capture': typeof CaptureRoute
  '/dev-preview': typeof DevPreviewRoute
  '/dogodki': typeof DogodkiRoute
  '/intel': typeof IntelRoute
  '/join': typeof JoinRoute
  '/lokacija': typeof LokacijaRoute
  '/misija': typeof MisijaRoute
  '/print': typeof PrintRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spartanops': typeof SpartanopsRoute
  '/spawn': typeof SpawnRoute
  '/updates': typeof UpdatesRoute
  '/api/send-inquiry': typeof ApiSendInquiryRoute
  '/api/send-reservation': typeof ApiSendReservationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-pregled'
    | '/archive'
    | '/arhiv'
    | '/capture'
    | '/dev-preview'
    | '/dogodki'
    | '/intel'
    | '/join'
    | '/lokacija'
    | '/misija'
    | '/print'
    | '/qr-generator'
    | '/scan'
    | '/sitemap.xml'
    | '/spartanops'
    | '/spawn'
    | '/updates'
    | '/api/send-inquiry'
    | '/api/send-reservation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-pregled'
    | '/archive'
    | '/arhiv'
    | '/capture'
    | '/dev-preview'
    | '/dogodki'
    | '/intel'
    | '/join'
    | '/lokacija'
    | '/misija'
    | '/print'
    | '/qr-generator'
    | '/scan'
    | '/sitemap.xml'
    | '/spartanops'
    | '/spawn'
    | '/updates'
    | '/api/send-inquiry'
    | '/api/send-reservation'
  id:
    | '__root__'
    | '/'
    | '/admin-pregled'
    | '/archive'
    | '/arhiv'
    | '/capture'
    | '/dev-preview'
    | '/dogodki'
    | '/intel'
    | '/join'
    | '/lokacija'
    | '/misija'
    | '/print'
    | '/qr-generator'
    | '/scan'
    | '/sitemap.xml'
    | '/spartanops'
    | '/spawn'
    | '/updates'
    | '/api/send-inquiry'
    | '/api/send-reservation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPregledRoute: typeof AdminPregledRoute
  ArchiveRoute: typeof ArchiveRoute
  ArhivRoute: typeof ArhivRoute
  CaptureRoute: typeof CaptureRoute
  DevPreviewRoute: typeof DevPreviewRoute
  DogodkiRoute: typeof DogodkiRoute
  IntelRoute: typeof IntelRoute
  JoinRoute: typeof JoinRoute
  LokacijaRoute: typeof LokacijaRoute
  MisijaRoute: typeof MisijaRoute
  PrintRoute: typeof PrintRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  ScanRoute: typeof ScanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpartanopsRoute: typeof SpartanopsRoute
  SpawnRoute: typeof SpawnRoute
  UpdatesRoute: typeof UpdatesRoute
  ApiSendInquiryRoute: typeof ApiSendInquiryRoute
  ApiSendReservationRoute: typeof ApiSendReservationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spawn': {
      id: '/spawn'
      path: '/spawn'
      fullPath: '/spawn'
      preLoaderRoute: typeof SpawnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spartanops': {
      id: '/spartanops'
      path: '/spartanops'
      fullPath: '/spartanops'
      preLoaderRoute: typeof SpartanopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misija': {
      id: '/misija'
      path: '/misija'
      fullPath: '/misija'
      preLoaderRoute: typeof MisijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokacija': {
      id: '/lokacija'
      path: '/lokacija'
      fullPath: '/lokacija'
      preLoaderRoute: typeof LokacijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogodki': {
      id: '/dogodki'
      path: '/dogodki'
      fullPath: '/dogodki'
      preLoaderRoute: typeof DogodkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-preview': {
      id: '/dev-preview'
      path: '/dev-preview'
      fullPath: '/dev-preview'
      preLoaderRoute: typeof DevPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arhiv': {
      id: '/arhiv'
      path: '/arhiv'
      fullPath: '/arhiv'
      preLoaderRoute: typeof ArhivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-pregled': {
      id: '/admin-pregled'
      path: '/admin-pregled'
      fullPath: '/admin-pregled'
      preLoaderRoute: typeof AdminPregledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-reservation': {
      id: '/api/send-reservation'
      path: '/api/send-reservation'
      fullPath: '/api/send-reservation'
      preLoaderRoute: typeof ApiSendReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-inquiry': {
      id: '/api/send-inquiry'
      path: '/api/send-inquiry'
      fullPath: '/api/send-inquiry'
      preLoaderRoute: typeof ApiSendInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPregledRoute: AdminPregledRoute,
  ArchiveRoute: ArchiveRoute,
  ArhivRoute: ArhivRoute,
  CaptureRoute: CaptureRoute,
  DevPreviewRoute: DevPreviewRoute,
  DogodkiRoute: DogodkiRoute,
  IntelRoute: IntelRoute,
  JoinRoute: JoinRoute,
  LokacijaRoute: LokacijaRoute,
  MisijaRoute: MisijaRoute,
  PrintRoute: PrintRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  ScanRoute: ScanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpartanopsRoute: SpartanopsRoute,
  SpawnRoute: SpawnRoute,
  UpdatesRoute: UpdatesRoute,
  ApiSendInquiryRoute: ApiSendInquiryRoute,
  ApiSendReservationRoute: ApiSendReservationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
